---
definitions:

resources:
  - &git-repo
    name: frontend-repo
    icon: github
    type: git
    source: &git-repo-source
      uri: git@github.com:alphagov/frontend.git
      branch: change-app-dir-owner
      private_key: | # pragma: allowlist secret
        ((govukci_private_key))

  - <<: *git-repo
    name: govuk-infrastructure
    source:
      <<: *git-repo-source
      uri: git@github.com:alphagov/govuk-infrastructure.git
      branch: main

  - &docker-image
    name: frontend-image
    type: registry-image
    icon: docker
    source: &docker-image-source
      repository: frontend
      tag: latest
      aws_region: ((concourse-ecr-user_aws-region))
      aws_access_key_id: ((concourse-ecr-user_aws-access-key))
      aws_secret_access_key: ((concourse-ecr-user_aws-secret-access-key))
      aws_role_arn: arn:aws:iam::((aws_production_account_id)):role/push_image_to_ecr_role

  - <<: *docker-image
    name: govuk-ruby-2.7.3
    source:
      <<: *docker-image-source
      repository: govuk-ruby-2.7.3
      tag: latest

  - &semver-version
    name: frontend-version
    type: semver
    source: &semver-version-source
      driver: s3
      access_key_id: ((readonly_access_key_id))
      secret_access_key: ((readonly_secret_access_key))
      session_token: ((readonly_session_token))
      bucket: ((readonly_private_bucket_name))
      key: frontend-version
      region_name: eu-west-2
      initial_version: '1.0.5'

jobs:

  - name: frontend
    serial: true
    plan:
    - in_parallel:
      - get: frontend-repo
        trigger: true
      - get: govuk-ruby-2.7.3
        params:
          format: oci
        trigger: true
      - get: frontend-version
        params:
          bump: minor
          pre_without_version: true
          pre: release
      - get: govuk-infrastructure
    - task: build-image
      privileged: true
      file: govuk-infrastructure/concourse/tasks/build-image-definition.yml
      input_mapping:
        git-repo: frontend-repo
        base-image: govuk-ruby-2.7.3
      params:
        IMAGE_ARG_base_image: base-image/image.tar
    - put: frontend-image
      params:
        image: image/image.tar
        additional_tags: frontend-version/version
    - in_parallel:
      - put: frontend-repo
        params:
          only_tag: true
          tag: frontend-version/version
          repository: frontend-repo
      - put: frontend-version
        params:
          file: frontend-version/version
