platform: linux
image_resource:
  type: registry-image
  source:
    repository: vito/oci-build-task
inputs:
- name: git-repo
outputs:
- name: image
params:
  CONTEXT: git-repo
  REGISTRY_MIRRORS: https://172025368201.dkr.ecr.eu-west-1.amazonaws.com
run:
  path: build
